name: Analyze

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.11.4
            
      - name: Install dependencies for App
        working-directory: comme_flutter
        run: flutter pub get

      - name: Install dependencies for Server
        working-directory: comme_server
        run: flutter pub get

      - name: Analyze Server
        working-directory: comme_server
        run: dart analyze --fatal-infos

      - name: Analyze App
        working-directory: comme_flutter
        run: dart analyze --fatal-infos